name: Build and Release PDF

on:
  push:
    tags:
      - 'v*'

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Typst
        uses: typst-community/setup-typst@v3
        
      - name: Build PDF
        run: |
          cd writeup
          typst compile main.typ main.pdf
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: writeup/main.pdf
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}